[project]
org-name = "vamosapi"
version = "0.0.1"
authors = ["nathancope@vamosdeploy.com"]
repository = "https://github.com/copenat/package-jira-service-desk"
keywords = ["ballerina", "jira", "jira7", "jira service desk"]
license = "Apache-2.0"
